// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKXvX42EL8XzSTdOcvt6Hgkc13Fljv9k',
    appId: '1:1074694647962:web:d0d2fc8fa4ecc3bfd72f23',
    messagingSenderId: '1074694647962',
    projectId: 'grocery-app-d3079',
    authDomain: 'grocery-app-d3079.firebaseapp.com',
    storageBucket: 'grocery-app-d3079.appspot.com',
    measurementId: 'G-NYBJLQ8WPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuO0GUhC74SnZmltt9snbWL_QcM_3v6pI',
    appId: '1:1074694647962:android:6e2ae2a7cfce4436d72f23',
    messagingSenderId: '1074694647962',
    projectId: 'grocery-app-d3079',
    storageBucket: 'grocery-app-d3079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBfJgBshnF1xG0MPaDmvrVGNZ23gETLAo',
    appId: '1:1074694647962:ios:f7cc2027ef822094d72f23',
    messagingSenderId: '1074694647962',
    projectId: 'grocery-app-d3079',
    storageBucket: 'grocery-app-d3079.appspot.com',
    iosBundleId: 'com.example.groceriesFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBfJgBshnF1xG0MPaDmvrVGNZ23gETLAo',
    appId: '1:1074694647962:ios:54abedc63af99446d72f23',
    messagingSenderId: '1074694647962',
    projectId: 'grocery-app-d3079',
    storageBucket: 'grocery-app-d3079.appspot.com',
    iosBundleId: 'com.example.groceriesFlutterApp.RunnerTests',
  );
}
